---
output:
  html_document: default
---
# Lab 4 - Working with raster data - the basics {#lab4}

So far, we have been working within the realm of vector data: beautiful topological combinations of vertices and lines to represent the complexity of the Earth's surface. But there are plenty of situations where vectors are not the best choice; any information that varies *gradually* and *continuously* over the surface can be better represented by *rasters*

For this exercise, we will learn to inspect and style raster data, and also how to do some mathematical operations among raster layers.

## Guided Exercise 1 - Opening and inspecting raster data

1. Download the required data from the link below:

2. Download additional data from [](https://gadm.org/). You want the offical country divisions for the United Kingdom. Pick Geopackage or Shapefile, your choice.
    
3. Open the four layers contained in the UK administrative boundary data. Keep the layer that shows only the overall boundaries for the UK, and remove the others from the project.

4. Add the `UK_SRTM.tif`, `UK_Bioclim.tif` and `CLC2018_CLC2018_V2018_20_UKclip.tif` raster files to your project. For each of them, right-click on the layer name and go to `Properties > Information`, then:

```{block type='rmdnote'}
**Stop and think:** 

- What are the datasets you have?

- What are the file *types* you have to work with?

- What are the file *formats* you have to work with?

- What are the *map projections* of each dataset you have (vector and raster)?

- What are the *lenght units* of each raster dataset?

- What are the *data types* of each raster dataset?

- What are the *dimensions (rows, columns)* of each raster dataset?

- How many *bands* does each raster dataset have?

- What are the *pixel sizes* of each raster dataset?
```

## Guided Exercise 2 - Styling raster data

1. Select the CORINE land cover data layer and go to `Properties > Symbology`. Not that the default symbology for single band rasters is `Singleband gray`. Change it to `Paletted / Unique Values`. Maintain the `Random Colors` option, and classify. Aplly the result to your raster and visualise it.

```{block type='rmdnote'}
**Stop and think:** 

- How many categories are there on this raster?

- What do the numbers represent?
```

2. Fortunately for us, the data producers of CORINE include a color map file as part of the *metadata*. Back on the *Symbology* window, click on the `...` to the right of `Delete All` and choose `Load Color Map from File...`. Find and select the metadata file named  `CLC2018_CLC2018_V2018_20_QGIS.txt`. `Apply` and then click `OK`. Thank you CORINE team! 

3. Now go to the *Symbology* window for the Bioclim dataset. Notice that the default symbology choice for multiband rasters is `Multiband color`. That option is appropriate for satellite images and aerial photography, where each band represents a different region of the electromagnetic spectrum, and then bands can be assigned to the Red, Green and Blue color channels of your screen. 

4. Since our data does not comprise images, but layers where pixel values represent *real variables*, we need to use the `Single band - pseudocolor` option. Choose the `bio1` band, and select the `magma` color ramp. `Classify` the existing values and then `Apply` and click `OK`.

```{block type='rmdnote'}
**Stop and think:** 

- What data is bio01 showing?

- What units are the minimum and maximum values shown on the color scale?

- Why such a strange choice for the units?
```

5. Return to the *Symbology* window, and expand the option `Min / Max Value Settings`. What is the default option selected? Experiment with the other options (with different percent clips and standard deviations) and see how the Symbology changes. Remember to `Apply` the changes every time you change any options.

6. Still on the *Symbology* window, change the `Classification` options (drop down menu to the left, under the classes) from `Continuous` to `Equal Interval`. To the right of it, select the numnber of classes as 3. `Apply` and evaluate.

7. Without changing your number of classes, change the `Interpolation` option above the classes from `Linear` to `Discrete`. `Apply` and evaluate. Take some time to play with these visualisation options to analyse the distribution of different Bioclimatic variables in the UK, and think what they mean for plants, (non-human) animals and in terms of social and economic factors.

8. Finally, let's work on the Symbology for the SRTM data. On the *Symbology* window, choose the `Singleband Pseudocolor` option, and then  on the `Color Ramp` option, select `Create New Color Ramp`. On the small options window that comes up, select `Catalog:cpt-city`.

9. Once the catalog window opens, go to the `Topography` list and select the `cd-a` palette. Then classify your elevation values using the `User Defined` Min /Max option, and type 0 as Min and 900 as Maximum. `Apply` and visualise. Then, befor closing the *Properties* window, go to the `Transparency` table and drag the slider at the top to around 60%.

10. Right-click on the SRTM layer name and select `Duplicate layer`. Then on the *Symbology* of the copied layer, change the `render type` to `Hillshade`. `Apply` and close the window. Make sure the copied layer is immediately under the original layer, and alternate each layer between on and off. 

```{block type='rmdnote'}
**Stop and think:** 

- What does the `hillshade` render style does? How? 

```

## Guided Exercise 3 - Mathematical and boolean operations using the Raster Calculator

## Guided Exercise 3 - Resampling, clipping, masking and reprojecting raster data

## Formative Exercise
